language: python
python:
  - "3.5"
dist: xenial
install:
  - sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
  - sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe'
  - sudo apt update
  - sudo apt install -y debootstrap
  - sudo debootstrap xenial xenial-test-chroot
  - sudo chroot xenial-test-chroot apt install -y software-properties-common
  - sudo chroot xenial-test-chroot apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
  - sudo chroot xenial-test-chroot apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe'
  - sudo chroot xenial-test-chroot apt-add-repository -y ppa:snappy-dev/image
  - sudo chroot xenial-test-chroot apt update
  - sudo chroot xenial-test-chroot apt install -y livecd-rootfs snapcraft pyflakes3 shellcheck make
  - sudo mkdir -p xenial-test-chroot/build
  - sudo cp -a Makefile snapcraft.yaml hooks live-build xenial-test-chroot/build
script:
  - sudo chroot xenial-test-chroot make check
  - sudo chroot xenial-test-chroot sh -c 'mount -t proc proc /proc; mount -t sysfs sys /sys; cd build; snapcraft'
