language: python
python:
  - "3.5"
dist: xenial
env:
  global:
    - URL=http://cdimage.ubuntu.com/ubuntu-base/releases/16.04/release/ubuntu-base-16.04-core-amd64.tar.gz
    - CHROOT=xenial-test-chroot
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
install:
  - mkdir -p $CHROOT/build
  - wget -q -O - $URL | zcat - | sudo tar x -C $CHROOT
  - sudo cp /etc/resolv.conf $CHROOT/etc/
  - sudo mount --bind /dev $CHROOT/dev
  - sudo chroot $CHROOT apt update
  - sudo chroot $CHROOT apt install -y software-properties-common
  - sudo chroot $CHROOT apt-add-repository -y ppa:snappy-dev/image
  - sudo sed -i '/^deb/s/$/ universe/' $CHROOT/etc/apt/sources.list
  - sudo chroot $CHROOT apt update
  - sudo chroot $CHROOT apt install -y livecd-rootfs snapcraft
  - sudo cp -a fc Makefile snapcraft.yaml hooks live-build $CHROOT/build
script:
  - sudo chroot $CHROOT sh -c 'mount -t proc proc /proc; mount -t sysfs sys /sys; cd build; snapcraft'
